apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 186478816830.dkr.ecr.us-east-1.amazonaws.com/voting-app/result:latest
        name: result
        ports:
        - containerPort: 80
          name: result
