apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 186478816830.dkr.ecr.us-east-1.amazonaws.com/voting-app/vote:latest
        name: vote
        ports:
        - containerPort: 80
          name: vote
