name: Buscar ALBs

on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches: [dev, test, main]

jobs:
  buscar-albs:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          
      - name: Obtener ELB que escucha en el puerto 8080
        id: elb_dns
        run: |
          echo "Buscando ELB que escuche en el puerto 8080..."

          vote=""

          elbs=$(aws elb describe-load-balancers \
          --query "LoadBalancerDescriptions[*].[LoadBalancerName,DNSName]" \
          --output text)

          while read -r name dns; do
            echo "Revisando $name ($dns)..."
            ports=$(aws elb describe-load-balancers \
              --load-balancer-name "$name" \
              --query "LoadBalancerDescriptions[0].ListenerDescriptions[*].Listener.LoadBalancerPort" \
              --output text)

          for port in $ports; do
            if [ "$port" = "8080" ]; then
              echo "✅ $name escucha en el puerto 8080"
              vote="$dns"
            fi
          done
          done <<< "$elbs"

          if [ -z "$vote" ]; then
            echo "❌ No se encontró ningún ELB que escuche en el puerto 8080"
            exit 1
          fi

          echo "DNS asignado a vote: $vote"

          # Evitar errores de output por formato
          echo "vote=$(echo "$vote" | tr -d '\n\r')" >> $GITHUB_OUTPUT
      
      - name: Usar ELB vote
        run: |
          echo "ELB que escucha en 8080: ${{ steps.elb_dns.outputs.vote }}"


