name: Buscar ALBs

on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches: [dev, test, main]

jobs:
  buscar-albs:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener DNS de los dos primeros ELBs
        run: |
          readarray -t dns_array < <(aws elb describe-load-balancers \
            --query "LoadBalancerDescriptions[*].DNSName" \
            --output text)

          dns1="${dns_array[0]}"
          dns2="${dns_array[1]}"

          echo "Primer ELB: $dns1"
          echo "Segundo ELB: $dns2"

          # Exportar como outputs si querés usarlos después
          echo "elb1=$dns1" >> $GITHUB_OUTPUT
          echo "elb2=$dns2" >> $GITHUB_OUTPUT
        id: elb_dns

      - name: Usar DNS obtenidos
        run: |
          echo "Usando ELB1: ${{ steps.elb_dns.outputs.elb1 }}"
          echo "Usando ELB2: ${{ steps.elb_dns.outputs.elb2 }}"

